version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: 18.2.0

    steps:
      - checkout
      - run:
          name: Install EAS CLI
          command: yarn add eas-cli@latest
      - run:
          name: Install dependencies
          command: yarn install

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - AY/deploy
