version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: 18.2.0

    steps:
      - checkout
      - run:
          name: Install EAS CLI
          command: yarn add eas-cli@latest
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build APK
          command: |
            EAS_USERNAME=$EXPO_USERNAME EAS_PASSWORD=$EXPO_PASSWORD npx eas build --platform android
      - run:
          name: login email
          command: echo "$EXPO_USERNAME"
      - run:
          name: login password
          command: echo "$EXPO_PASSWORD"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
